# .air.toml

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Binary file name
bin = "tmp/main"

# Build command
cmd = "go build -o ./tmp/main ./cmd/server"

# Run the binary
full_bin = "./tmp/main"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "node_modules"]
delay = 1000

# Send Interrupt signal (SIGINT) before killing process (SIGKILL)
send_interrupt = true

# Delay in milliseconds before force killing the process
kill_delay = 500

# Stop running old binary when build errors occur
stop_on_error = true

[log]
time = true

[color]
app = "cyan"
build = "yellow"
watcher = "magenta"
